### ISSUE TITLE
use catch for unit tests

### ISSUE THREAD

**Issue by arvidn** [bittorrent/bootstrap-dht#11]
I'm tempted to pull in catch.hpp to use for tests. Does that seem reasonable? Are there other light-weight test frameworks that may be better options?

**Comment by ssiloti** [comment]
I'm not really up on the latest in unit test frameworks, but catch seems reasonable.

**Comment by arvidn** [comment]
while adding unit tests I found a few bugs in the recent patches I've pulled. So, unless it's obvious, master is not in a releasable state right now

**Comment by arvidn** [comment]
https://github.com/bittorrent/bootstrap-dht/pull/17
