### ISSUE TITLE
Not sure where to ask

### ISSUE THREAD

**Issue by adamreed90** [bittorrent/bootstrap-dht#24]
I'm not sure where else to ask this:

I was bootstrapping last night to 

```
                new IPEndPoint(Dns.GetHostEntry("router.utorrent.com").AddressList[0], 6881),
                new IPEndPoint(Dns.GetHostEntry("router.bittorrent.com").AddressList[0], 6881),
                new IPEndPoint(Dns.GetHostEntry("dht.aelitis.com").AddressList[0], 6881)
```

quite repeatedly while debugging my application, and today I cannot get responses from any of these hosts. Is it possible i've been banned/blocked?

**Comment by arvidn** [comment]
I just tested `router.utorrent.com:6881` and it works fine for me. You can try this:
`python test_dht.py router.utorrent.com 6881`

**Comment by arvidn** [comment]
btw.. you may want to be a bit more sophisticated in how you pick an IP from the hostname resolver. If one fails, you may want to try the next one. and if you're looking for IPv4 addresses, you may want to filter IPv6 etc. It's probably a good idea to only hit one of the returned IPs though, rather all of them

**Comment by adamreed90** [comment]
Thanks I'll give that a try.

**Comment by adamreed90** [comment]
Ouch =\ That didn't work. 

D:\Development\bootstrap-dht-master>py test_dht.py router.utorrent.com 6881
  File "test_dht.py", line 16
    print msg
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by adamreed90** [comment]
The test worked perfect, so I can only assume I messed up my bootstrapping somewhere. 

I sniffed the query that test was sending, and I noticed that it is only sending 3 byes:

`ASCII:d1:ad2:id20:.1:..........J.D...(6:target20:x....R..8...L./q.H..e1:q9:find_node1:t3:1701:y1:qe`
Being:
```
{
 {"a", {"id", byte[20] } },
 {"q", byte[9]("find_node")},
 {"t", byte[3]("170")},
 {"y", byte[1]("q")}
}
```

From the documentation @ http://www.bittorrent.org/beps/bep_0005.html shouldn't `"t"` be a `byte[20]` containing a target ID?

**Comment by arvidn** [comment]
no,`t` is transaction id. it's a string that gets echoed back in the response

**Comment by adamreed90** [comment]
Ah, I see now, thank you! =D
