### ISSUE TITLE
bootstrap

### ISSUE THREAD

**Issue by gushenghua** [bittorrent/bootstrap-dht#43]
should bootstrap(router.bitorrent.com) be specified when start the process?

**Comment by arvidn** [comment]
no, but some other arguments should be specified.

**Comment by gushenghua** [comment]
how does the server join DHT without bootstrap node?

**Comment by arvidn** [comment]
this *is* the bootstrap node. but there is a "cross pollinate" feature to seed a bootstrap instance from another one

**Comment by gushenghua** [comment]
I see, thank you
