### ISSUE TITLE
Error during the build.

### ISSUE THREAD

**Issue by amirnn** [bittorrent/bootstrap-dht#50]
I tried the instructions for the build in the read-me. However, The new versions of boost don't have a sha1.hpp under uuid. That's my guess, for the cause of the problem. I created a fork to fix this but I am not sure this is the optimal way of doing it.

Either one should refer to previous version of boost. Or reflect the changes to the code. Also, as a side note, I could not find the version of the boost used for compiling this project.

blahbalh/bootstrap-dht-master/src/main.cpp:51:10: fatal error: 'boost/uuid/sha1.hpp' file not found
#include <boost/uuid/sha1.hpp>

I checked the boost library, and the sha1.hpp exists until version 1.67.

Best,
Amir

**Comment by amirnn** [comment]
To fix the build under newer versions of the boost one needs to include the sha1 header from: 
"<boost/uuid/detail/sha1.hpp>"

Basically, replace the previous location of this file with the new one above. Also, I am including my cmake file to compile the project in case anybody else wants a quick ref.

cmake_minimum_required(VERSION 3.0)
project(bootstrap_dht)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Boost REQUIRED COMPONENTS system)
include_directories(${Boost_INCLUDE_DIRS})

add_executable(bootstrap_dht
        src/bdecode.cpp
        src/city.cc
        src/ip_set.cpp
        src/main.cpp)

target_link_libraries(bootstrap_dht Boost::system)

**Comment by milahu** [comment]
fixed by #51
